ConsumeWebAPI/Models/ServerDataModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace ConsumeWebAPI.Models
{
    public class ServerDataModel
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Initial date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime InitialDate { get; set; }
        [Required]
        [Display(Name = "End date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime EndDate { get; set; }

        [Required]
        [Display(Name = "Order number")]
        public int OrderNumber { get; set; }
        [Required]
        [Display(Name = "Is dirty")]
        public bool IsDirty { get; set; }
        [Required, StringLength(15)]
        [Display(Name = "Data Server IP")]
        [RegularExpression(@"^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$",ErrorMessage = "Data Server IP should be in the form of 255.255.255")]
        public string IP { get; set; }

        [Required]
        [Display(Name = "Record data type")]
        [RegularExpression(@"^([1-2])$", ErrorMessage = "Record Data Type should be 1 or 2")]
        public int Type { get; set; }

        [Display(Name = "Record identifier")]
        [RegularExpression(@"^([0-9])$", ErrorMessage = "Record identifier should be between 0 to 9")]
        public int RecordIdentifier { get; set; }
    }
}

ConsumeWebAPI/Controllers/HomeController.cs
using System.Web.Mvc;

namespace ConsumeWebAPI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "This is a demo app showing how to consume asp.net web api using RestSharp.";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "About demo app.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Contact page.";

            return View();
        }
    }
}

ConsumeWebAPI/Controllers/ServerDataController.cs
using System.Web.Mvc;
using ConsumeWebAPI.Helper;
using ConsumeWebAPI.Models;

namespace ConsumeWebAPI.Controllers
{
    public class ServerDataController : Controller
    {
        static readonly IServerDataRestClient RestClient = new ServerDataRestClient();
        //
        // GET: /ServerData/

        public ActionResult Index()
        {
            return View(RestClient.GetAll());
        }

        //
        // GET: /ServerData/Details/5

        public ActionResult Details(int id)
        {
            return View(RestClient.GetById(id));
        }

        //
        // GET: /ServerData/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /ServerData/Create

        [HttpPost]
        public ActionResult Create(ServerDataModel serverData)
        {
            try
            {
                RestClient.Add(serverData);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /ServerData/Edit/5

        public ActionResult Edit(int id)
        {
            return View(RestClient.GetById(id));
        }

        //
        // POST: /ServerData/Edit/5

        [HttpPost]
        public ActionResult Edit(ServerDataModel serverData)
        {
            try
            {
                RestClient.Update(serverData);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /ServerData/Delete/5

        public ActionResult Delete(int id)
        {
            return View(RestClient.GetById(id));
        }

        //
        // POST: /ServerData/Delete/5

        [HttpPost]
        public ActionResult Delete(ServerDataModel serverData)
        {
            try
            {
                RestClient.Delete(serverData.Id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ConsumeWebAPI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        This is a demo application showing how to consume ASP.Net WEB API using ASP.NET MVC4 and RestSharp.
    </p>

</article>

<aside>
    <h3>Navigation</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("Manipulate Data", "Index", "ServerData")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

ConsumeWebAPI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:gaurav@gaurav-arora.com">gaurav@gaurav-arora.com</a></span>
    </p>
    <header>
        <h3>Web</h3>
    </header>
    <p>
        <span class="label">Web Site:</span>
        <span><a href="http://gaurav-arora.com">Gaurav Arora's Blog</a></span>
    </p>
    <p>
        <span class="label">Creating ASP.Net WebAPi:</span>
        <span><a href="http://gaurav-arora.com/crud-operations-with-asp-net-web-api-using-fluentnhibernate-repository-pattern/">Demo :: ASP.Net Web API </a></span>
    </p>

</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

ConsumeWebAPI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
            <p>
                To learn more about this article visit
                <a href="http://asp.net/mvc" title="ASP.NET MVC Website">http://asp.net/mvc</a>.
                This describes <mark>how to consume ASP.NET WEB API using RestSharp</mark>.
                If you have any questions about ASP.NET MVC visit
                <a href="http://forums.asp.net/1146.aspx/1?MVC" title="ASP.NET MVC Forum">our forums</a>.
            </p>
        </div>
    </section>
}
<h3>We suggest the following:</h3>
<ol class="round">
    <li class="one">
        <h5>Getting Started</h5>
        Before going through this article, you should read my earlier article where I
        described <mark>CRUD Operations with ASP.Net Web API using FluentNHibernate, Repository pattern</mark>.
        <a href="http://gaurav-arora.com/crud-operations-with-asp-net-web-api-using-fluentnhibernate-repository-pattern/" title="Crud Operations aspnet webapi">Learn more…</a>
    </li>

    <li class="two">
        <h5>Get WEB API URIs</h5>
        You can see complete list of WEB API URIs and try with your own application.
        <a href="http://crudwithwebapi.azurewebsites.net/" title="Demo crudwithwebapi">Check here</a>
    </li>

    <li class="three">
        <h5>More updates</h5>
        You can find more update by joining our page. Here we offer many exciting things. Free <mark>
                                                                                                   online/offline training, videos, articles, news</mark> etc.
        <a href="https://facebook.com/blog.gaurav" title="Facebook page of Gaurav Arora">Join us</a>
    </li>
    <li class="four">
        <h5>Source code</h5>
        You can download and use the complete source. <a href="https://github.com/garora/somestuff/tree/master/consumewebapi" title="Download source code">Download</a>
    </li>
</ol>

ConsumeWebAPI/Views/ServerData/Create.cshtml
@model ConsumeWebAPI.Models.ServerDataModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create new record of ServerData</h2>

<article>
    <p>
        Here you can manipulat server data.
    </p>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <fieldset>
            <legend>ServerDataModel</legend>

            <div class="label">
                @Html.LabelFor(model => model.InitialDate)
            </div>
            <div class="label">
                @Html.EditorFor(model => model.InitialDate)
                @Html.ValidationMessageFor(model => model.InitialDate)
            </div>

            <div class="label">
                @Html.LabelFor(model => model.EndDate)
            </div>
            <div class="label">
                @Html.EditorFor(model => model.EndDate)
                @Html.ValidationMessageFor(model => model.EndDate)
            </div>

            <div class="label">
                @Html.LabelFor(model => model.OrderNumber)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.OrderNumber)
                @Html.ValidationMessageFor(model => model.OrderNumber)
            </div>

            <div class="label">
                @Html.LabelFor(model => model.IsDirty)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.IsDirty)
                @Html.ValidationMessageFor(model => model.IsDirty)
            </div>

            <div class="label">
                @Html.LabelFor(model => model.IP)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.IP)
                @Html.ValidationMessageFor(model => model.IP)
            </div>

            <div class="label">
                @Html.LabelFor(model => model.Type)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Type)
                @Html.ValidationMessageFor(model => model.Type)
            </div>

            <div class="label">
                @Html.LabelFor(model => model.RecordIdentifier)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.RecordIdentifier)
                @Html.ValidationMessageFor(model => model.RecordIdentifier)
            </div>

            <p>
                <input type="submit" value="Create" />  @Html.ActionLink("Cancel", "Index", null, new { @class = "actionlinkbutton" })
            </p>
        </fieldset>
    }
</article>
<aside>
    <h3>Navigation</h3>
    <p>
        From here you can navigate other parts of app.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("Manipulate Data", "Index", "ServerData")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ConsumeWebAPI/Views/ServerData/Delete.cshtml
@model ConsumeWebAPI.Models.ServerDataModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Consume Asp.net WebAPI :: Delete</h2>

<article>
    <p>
        Here you can manipulat server data.
    </p>
    <h3>Are you sure you want to delete this?</h3>
    <fieldset>
        <legend>ServerDataModel</legend>

        <div class="label">
            @Html.DisplayNameFor(model => model.InitialDate)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.InitialDate)
        </div>

        <div class="label">
            @Html.DisplayNameFor(model => model.EndDate)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.EndDate)
        </div>

        <div class="label">
            @Html.DisplayNameFor(model => model.OrderNumber)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.OrderNumber)
        </div>

        <div class="label">
            @Html.DisplayNameFor(model => model.IsDirty)
        </div>
        <div class="display-field">
            @string.Format(Model.IsDirty ? "Yes" : "No")
        </div>

        <div class="label">
            @Html.DisplayNameFor(model => model.IP)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.IP)
        </div>

        <div class="label">
            @Html.DisplayNameFor(model => model.Type)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Type)
        </div>

        <div class="label">
            @Html.DisplayNameFor(model => model.RecordIdentifier)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.RecordIdentifier)
        </div>
    </fieldset>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <p>
            <input type="submit" value="Delete" /> @Html.ActionLink("Cancel", "Index", null, new { @class = "actionlinkbutton" })
        </p>
    }
</article>

<aside>
    <h3>Navigation</h3>
    <p>
        From here you can navigate other parts of app.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("Manipulate Data", "Index", "ServerData")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

ConsumeWebAPI/Views/ServerData/Details.cshtml
@model ConsumeWebAPI.Models.ServerDataModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Consume Asp.net WebAPI :: Details</h2>
<article>
    <p>
        Here you can manipulat server data.
    </p>

    <fieldset>
        <div class="label">
            @Html.DisplayNameFor(model => model.Id)
        </div>
        <div class="label">
            @Html.DisplayNameFor(model => model.InitialDate)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.InitialDate)
        </div>
        <div class="label">
            @Html.DisplayNameFor(model => model.EndDate)
        </div>
        <div class="label">
            @Html.DisplayNameFor(model => model.EndDate)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.OrderNumber)
        </div>
        <div class="display-field">
            @Html.DisplayNameFor(model => model.IsDirty)
        </div>
        <div class="label">
            @string.Format(Model.IsDirty ? "Yes" : "No")
        </div>
        <div class="label">
            @Html.DisplayNameFor(model => model.IP)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.IP)
        </div>
    </fieldset>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "actionlinkbutton" }) @Html.ActionLink("Cancel", "Index", null, new { @class = "actionlinkbutton" })
    </p>
</article>

<aside>
    <h3>Navigation</h3>
    <p>
        From here you can navigate other parts of app.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("Manipulate Data", "Index", "ServerData")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

ConsumeWebAPI/Views/ServerData/Edit.cshtml
@model ConsumeWebAPI.Models.ServerDataModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Consume Asp.net WebAPI :: Edit</h2>
<article>
    <p>
        Here you can manipulat server data.
    </p>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <fieldset>
            @Html.HiddenFor(model => model.Id)

            <div class="label">
                @Html.LabelFor(model => model.InitialDate)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.InitialDate)
                @Html.ValidationMessageFor(model => model.InitialDate)
            </div>

            <div class="label">
                @Html.LabelFor(model => model.EndDate)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.EndDate)
                @Html.ValidationMessageFor(model => model.EndDate)
            </div>

            <div class="label">
                @Html.LabelFor(model => model.OrderNumber)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.OrderNumber)
                @Html.ValidationMessageFor(model => model.OrderNumber)
            </div>

            <div class="label">
                @Html.LabelFor(model => model.IsDirty)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.IsDirty)
                @Html.ValidationMessageFor(model => model.IsDirty)
            </div>

            <div class="label">
                @Html.LabelFor(model => model.IP)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.IP)
                @Html.ValidationMessageFor(model => model.IP)
            </div>

            <div class="label">
                @Html.LabelFor(model => model.Type)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Type)
                @Html.ValidationMessageFor(model => model.Type)
            </div>

            <div class="label">
                @Html.LabelFor(model => model.RecordIdentifier)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.RecordIdentifier)
                @Html.ValidationMessageFor(model => model.RecordIdentifier)
            </div>

            <p>
                <input type="submit" value="Save" /> @Html.ActionLink("Cancel", "Index", null, new { @class = "actionlinkbutton" })
            </p>
        </fieldset>
    }


</article>

<aside>
    <h3>Navigation</h3>
    <p>
        From here you can navigate other parts of app.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("Manipulate Data", "Index", "ServerData")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ConsumeWebAPI/Views/ServerData/Index.cshtml
@model IEnumerable<ConsumeWebAPI.Models.ServerDataModel>

@{
    ViewBag.Title = "Manipulate Server Data";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Consume Asp.net WebAPI :: Server Data</h2>

<article>
    <p>
        Here you can manipulat server data.
    </p>

    <p>
        @Html.ActionLink("Create New", "Create", null, new { @class = "actionlinkbutton" })
    </p>

    <div>
        <table>

            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.InitialDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.EndDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OrderNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsDirty)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IP)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Type)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RecordIdentifier)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.InitialDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EndDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.OrderNumber)
                    </td>
                    <td>
                        @string.Format(item.IsDirty ? "Yes" : "No")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IP)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RecordIdentifier)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }

        </table>
    </div>
</article>

<aside>
    <h3>Navigation</h3>
    <p>
        From here you can navigate other parts of app.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("Manipulate Data", "Index", "ServerData")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>